"""The vault is a git repo. One commit per note; push is best-effort."""
from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path
from typing import Optional

log = logging.getLogger("sme.vault")


def _git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, text=True, timeout=120
    )
    if check and proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc


def chown_tree(path: Path, uid: Optional[int], gid: Optional[int]) -> None:
    """Hand ownership of the vault to a real host user.

    The container writes as root. On a bind-mounted vault that leaves every note
    root-owned, which reads fine but blocks editing from the host or over Samba —
    and Obsidian wants to write (.obsidian/, edits). No-op when unset.
    """
    if uid is None or gid is None:
        return
    try:
        for root, dirs, files in os.walk(path):
            for name in dirs + files:
                try:
                    os.chown(os.path.join(root, name), uid, gid)
                except (PermissionError, FileNotFoundError):
                    pass
        os.chown(path, uid, gid)
    except (PermissionError, FileNotFoundError) as e:
        log.warning("could not chown vault to %s:%s (%s)", uid, gid, e)


def chown_path(path: Path, uid: Optional[int], gid: Optional[int]) -> None:
    if uid is None or gid is None:
        return
    try:
        os.chown(path, uid, gid)
    except (PermissionError, FileNotFoundError):
        pass


def ensure_repo(repo: Path, *, branch: str, author_name: str, author_email: str,
                remote: str = "", uid: Optional[int] = None, gid: Optional[int] = None) -> None:
    repo.mkdir(parents=True, exist_ok=True)
    if not (repo / ".git").exists():
        _git(repo, "init", "-b", branch)
        log.info("initialised vault repo at %s", repo)
    _git(repo, "config", "user.name", author_name)
    _git(repo, "config", "user.email", author_email)
    # Container uid may differ from the volume's owner; git refuses to operate otherwise.
    subprocess.run(
        ["git", "config", "--global", "--add", "safe.directory", str(repo)],
        capture_output=True, text=True,
    )
    if remote:
        existing = _git(repo, "remote", check=False).stdout.split()
        if "origin" in existing:
            _git(repo, "remote", "set-url", "origin", remote)
        else:
            _git(repo, "remote", "add", "origin", remote)
    if not (repo / "README.md").exists():
        (repo / "README.md").write_text(
            "# Reel vault\n\nGenerated by social-media-data-extractor. "
            "Notes live in `reels/`. Do not hand-edit frontmatter.\n",
            encoding="utf-8",
        )
    chown_tree(repo, uid, gid)


def commit_note(repo: Path, note_path: Path, message: str) -> bool:
    """Stage and commit one note. Returns False when there was nothing to commit."""
    rel = note_path.relative_to(repo)
    _git(repo, "add", "--", str(rel))
    if not _git(repo, "diff", "--cached", "--quiet", check=False).returncode:
        return False
    _git(repo, "commit", "-m", message)
    return True


def push(repo: Path, branch: str) -> tuple[bool, str]:
    proc = _git(repo, "push", "-u", "origin", branch, check=False)
    if proc.returncode == 0:
        return True, ""
    return False, (proc.stderr or proc.stdout).strip()[-500:]
